---

- name: Create bacula group
  group:
    name: bacula
    state: present

- name: Create bacula user
  user:
    state: present
    name: bacula
    shell: /bin/bash
    home: '/home/bacula'

- name: Create backup directory
  file:
    path: "{{ bacula_backup_dir }}"
    state: directory
    owner: bacula
    group: bacula
    mode: 0770

- name: Automatically mount external hard drive
  lineinfile:
    path: /etc/fstab
    regexp: '\# Backup volume'
    state: present
    line: "{{ bacula_block_device }} {{ bacula_backup_dir }} ext4 defaults,nosuid,nodev,nofail,noauto 0 0  # Backup volume"

- name: Configure logrotate
  copy:
    remote_src: true
    src: "{{ bacula_source_dir }}/bacula/scripts/logrotate"
    dest: "/etc/logrotate.d/bacula"

- name: Configure Postgres to allow md5 auth
  lineinfile:
    path: /etc/postgresql/13/main/pg_hba.conf
    state: present
    line: "local bacula {{ bacula_database_username }} md5"
    insertbefore: '# DO NOT DISABLE!'

# - name: Configure Bacula Director
#   template:
#     src: etc/bacula/bacula-dir.conf.j2
#     dest: /etc/bacula/bacula-dir.conf
#     owner: root
#     group: bacula
#     mode: 0640
#
# - name: Configure Bacula File Daemon
#   template:
#     src: etc/bacula/bacula-fd.conf.j2
#     dest: /etc/bacula/bacula-fd.conf
#     owner: root
#     group: bacula
#     mode: 0640
#
# - name: Configure Bacula Storage Daemon
#   template:
#     src: etc/bacula/bacula-sd.conf.j2
#     dest: /etc/bacula/bacula-sd.conf
#     owner: bacula
#     group: bacula
#     mode: 0640
#
# - name: Configure Bacula Console
#   template:
#     src: etc/bacula/bconsole.conf.j2
#     dest: /etc/bacula/bconsole.conf
#     owner: root
#     group: bacula
#     mode: 0640
#
# - name: Update Postgresql user
#   postgresql_user:
#     db: bacula
#     name: bacula
#     password: "{{ bacula_catalog_password }}"
#   become: true
#   become_user: postgres
