---

- name: 'Bacula Sanity check #1'
  fail:
    msg: "Breh, you can't be both client and server. Server has everything anyways."
  when: bacula_server and bacula_client

- name: 'Bacula Sanity check #2'
  fail:
    msg: "Bacula needs to know if it should be a server or client"
  when: not bacula_server and not bacula_client

- include: 'build.yml'
  become: yes
  become_user: root
  when: bacula_client or bacula_server

- include: 'configure-server.yml'
  become: yes
  become_user: root
  when: bacula_server
